/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 flask.glb --types --transform 
Files: flask.glb [34.58KB] > C:\Users\hashi\OneDrive\Desktop\banana-flask-3d\flask-transformed.glb [27.1KB] (22%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    pCylinder3: THREE.Mesh;
  };
  materials: {
    ["Glass.001"]: THREE.MeshStandardMaterial;
  };
};

export function FlaskModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/flask-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.pCylinder3.geometry}
        material={materials["Glass.001"]}
        position={[0, -0.011, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.048}
      />
    </group>
  );
}

useGLTF.preload("/flask-transformed.glb");
